console.log("loaded!");

const queryString = window.location.search;
const urlParams = new URLSearchParams(queryString);
let brand = urlParams.has("brand")
  ? urlParams.get("brand")
  : "Costco Wholesale";
let region = urlParams.has("region")
  ? urlParams.get("region")
  : "United States";
let compare = urlParams.has("compare") ? urlParams.get("compare") : "3";
let regionType = "nationwide";
let aggregation = "Daily";

document.getElementById("select-brand").value = brand;
document.getElementById("select-region").value = region;
document.getElementById("select-compare").value = compare;

console.log("loaded!!!");

/* SEO Title */
function updatePageTitle() {
  const title = `${brand} Brand Tracker in ${region}`;
  document.querySelector("#brand-tracker-title").innerText = title;
}

updatePageTitle();

/* Tableau Viz */
let viz;
function initViz() {
  let containerDiv = document.getElementById("vizContainer");
  let url =
    "https://tableau-labs.placer.ai/#/site/TheSquare/views/BrandTracker/Corona_brandtracker";
  let options = {
    hideTabs: true,
    hideToolbar: true,
    onFirstInteractive: function () {
      switchBrand(brand);
      switchRegion(region);
      switchDate(compare);
    },
  };

  // If a viz object exists, delete it.
  if (viz) {
    viz.dispose();
  }

  // Create new viz object
  viz = new tableau.Viz(containerDiv, url, options);
}

window.addEventListener("load", initViz);

/* Switch Tableau Params */
function switchBrand(param) {
  viz.getWorkbook().changeParameterValueAsync("BrandParam", param);
}
function switchDate(param) {
  viz
    .getWorkbook()
    .changeParameterValueAsync("comparison", compareValues(param));
}
function switchRegion(param) {
  viz.getWorkbook().changeParameterValueAsync("RegionParam", param);
  const newArea = param == "United States" ? "Nationwide" : "By State";
  updateArea(newArea);
}
function updateArea(area) {
  document.getElementById("area").innerText = area;
}
function compareValues(param) {
  let compare = "";
  switch (param) {
    case "1":
      compare = "Previous Year";
      break;
    case "2":
      compare = "Two Years Ago";
      break;
    case "3":
    default:
      compare = "Three Years Ago";
  }
  console.log(compare);
  return compare;
}

/* History API */
function updateURL() {
  let urlParams = "";

  if (brand !== "All") {
    urlParams += `brand=${brand}`;
  }
  if (region !== "All") {
    urlParams += urlParams === "" ? "" : "&";
    urlParams += `category=${region}`;
  }
  if (compare !== "3") {
    urlParams += urlParams === "" ? "" : "&";
    urlParams += `compare=${compare}`;
  }

  urlParams = urlParams === "" ? "" : `?${urlParams}`;

  window.history.pushState(null, null, urlParams);
}

/* Selectize */
jQuery(document).ready(function () {
  jQuery("#select-brand").selectize({
    onChange: function (value) {
      brand = value;
      updateURL();
      updatePageTitle();
      switchBrand(value);
    },
  });

  jQuery("#select-region").selectize({
    onChange: function (value) {
      region = value;
      updateURL();
      updatePageTitle();
      switchRegion(value);
    },
  });

  jQuery("#select-compare").selectize({
    onChange: function (value) {
      compare = value;
      updateURL();
      updatePageTitle();
      switchDate(value);
    },
  });
});

let brandOptions = [
  "7-Eleven",
  "24 Hour Fitness",
  "99 Cents Only Stores",
  "99 Ranch Market",
  "Abby's Legendary Pizza",
  "ABC Fine Wine & Spirits",
  "ABC Warehouse",
  "Abuelo's",
  "Academy Sports + Outdoors",
  "Ace Hardware",
  "ACME Markets",
  "Advance Auto Parts",
  "Albertsons",
  "Aldi",
  "Alterra Mountain Company",
  "AMC Theatres",
  "America's Tire Store",
  "American Asset Corporation",
  "American Tire Depot",
  "Americas Best Value Inn",
  "AmericInn",
  "Anthony's Coal Fired Pizza",
  "Anytime Fitness",
  "Applebee's",
  "Arby's",
  "Arctic Circle",
  "Ashley Furniture HomeStore",
  "At Home",
  "Aubuchon Hardware",
  "Autobell Car Wash",
  "AutoZone",
  "Back Yard Burgers",
  "Bad Daddy's Burger Bar",
  "Bahama Breeze",
  "Bahama Bucks",
  "Baja Fresh",
  "Bank of America",
  "Bank of the West",
  "Bar Louie",
  "Bargain Hunt",
  "Barnes & Noble",
  "Barons Market",
  "Bartell Drugs",
  "Bashas'",
  "Bass Pro Shops",
  "Baymont Inn & Suites",
  "BB&T",
  "Bealls Florida",
  "Bealls Outlet",
  "Bed Bath & Beyond",
  "Belk",
  "Belle Tire",
  "Benihana",
  "Bertucci's",
  "Best Buy",
  "Best Western",
  "BevMo!",
  "Bi-Lo",
  "Bi-Mart",
  "Big 5 Sporting Goods",
  "Big Lots",
  "Big O Tires",
  "Big R",
  "Big Y World Class Market",
  "BIGGBY COFFEE",
  "Bill Miller Bar-B-Q",
  "Binny's Beverage Depot",
  "BJ's Restaurant and Brewhouse",
  "BJ's Wholesale Club",
  "Black Angus Steakhouse",
  "Black Bear Diner",
  "Blain's Farm & Fleet",
  "Blake's LotaBurger",
  "Bloomingdale's",
  "Bloomingdale's Outlet",
  "Board & Brew",
  "Bob Evans Restaurant",
  "Bob's Discount Furniture",
  "Bojangles' Famous Chicken 'n Biscuits",
  "Bonefish Grill",
  "Books-A-Million",
  "Boot Barn",
  "Boscov's",
  "Boston Market",
  "Brake Check",
  "Brake Masters",
  "Brakes Plus",
  "Braum's Ice Cream & Dairy Stores",
  "Brio Tuscan Grille",
  "Bristol Farms",
  "Brixmor Property Group",
  "Brookfield Properties Retail Group",
  "Brookshire Brothers",
  "Brookshire's",
  "Bruster's",
  "Bubba's 33",
  "Buca di Beppo Italian Restaurant",
  "Buffalo Wild Wings",
  "Buffalo Wings & Rings",
  "Burger King",
  "BURGERFI",
  "Burkes Outlet",
  "Burlington",
  "Bush's Chicken",
  "buybuy BABY",
  "C-Town Supermarkets",
  "Cabela's",
  "Caesars Entertainment Casinos",
  "Inc",
  "Cafe Rio Mexican Grill",
  "Cafe Zupas",
  "California Pizza Kitchen",
  "Camping World",
  "Candlewood Suites",
  "Captain D's",
  "Car Toys",
  "Cardenas Market",
  "Carl's Jr.",
  "CarMax",
  "Carrabba's Italian Grill",
  "Cavender's Boot City",
  "CBL Mall Properties",
  "Central Market",
  "Chase Bank",
  "Checkers",
  "Cheddar's Scratch Kitchen",
  "Chick-fil-A",
  "Chicken Express",
  "Chili's Grill & Bar",
  "Chipotle Mexican Grill",
  "Christian Brothers Automotive",
  "Christmas Tree Shops",
  "Chuck E. Cheese's",
  "Church's Chicken",
  "Chuy's",
  "Chuze Fitness",
  "Cinemark",
  "Citi Trends",
  "Citibank",
  "City Barbeque",
  "Colton's Steak House & Grill",
  "Columbia Bank",
  "Comfort Inn & Suites",
  "Commerce Bank",
  "Community Health Systems",
  "Concentra Urgent Care",
  "Conn's HomePlus",
  "Cook Out",
  "Cooper's Hawk Winery & Restaurant",
  "Corner Bakery Cafe",
  "Cost Plus World Market",
  "Costa Vida",
  "Costco Wholesale",
  "Cotton Patch Cafe",
  "Country Inn & Suites",
  "Courtyard by Marriott",
  "Cousins Subs",
  "Cowboy Chicken",
  "Cracker Barrel Old Country Store",
  "Crate and Barrel",
  "Crowne Plaza",
  "Crunch Fitness",
  "Cub Foods",
  "Culver's",
  "Cumberland Farms",
  "CVS/pharmacy",
  "D'Angelo Grilled Sandwiches",
  "Dairy Queen",
  "Dave & Buster's",
  "David's Bridal",
  "Days Inn",
  "Del Taco",
  "Denny's",
  "Deseret Industries",
  "Dick's Sporting Goods",
  "Dillard's",
  "Dillons",
  "Discount Drug Mart",
  "Discount Tire Store",
  "Dollar General",
  "Dollar Tree",
  "Donatos Pizza",
  "DSW Designer Shoe Warehouse",
  "Dunham's Sports",
  "Dunkin' Donuts",
  "Dutch Bros. Coffee",
  "Eat'n Park",
  "Econo Lodge",
  "Edens Properties",
  "Eegee's",
  "El Pollo Loco",
  "El Pollo Regio",
  "El Rancho Supermercado",
  "El Rio Grande",
  "El Super",
  "Embassy Suites",
  "EoS Fitness",
  "Express Oil Change",
  "Extended Stay America",
  "Eyeglass World",
  "Fairfield Inn",
  "Family Dollar",
  "Family Fare",
  "Family Farm & Home",
  "Family Video",
  "Famous Dave's",
  "Fareway",
  "Farmer Boys",
  "FastMed Urgent Care",
  "Fazoli's",
  "Federal Realty Investment Trust",
  "Festival Foods",
  "Field & Stream",
  "Fiesta Mart",
  "Fifth Third Bank & ATM",
  "Fine Fare",
  "Firebirds Wood Fired Grill",
  "Firestone Complete Auto Care",
  "First Washington Realty",
  "First Watch",
  "Fitness 19",
  "Fitness Connection",
  "Five Below",
  "Flash Foods",
  "Fleming's Prime Steakhouse & Wine Bar",
  "Floor & Decor",
  "Food 4 Less",
  "Food City",
  "Food City Arizona",
  "Food Giant",
  "Food Lion Grocery Store",
  "FoodMaxx",
  "Fosters Freeze",
  "Four Points by Sheraton",
  "Fred Meyer",
  "Freddy's Frozen Custard & Steakburgers",
  "Fresh Thyme Farmers Market",
  "Frisch's Big Boy",
  "Fry's Electronics",
  "Frys",
  "Fuddruckers",
  "Furniture Row",
  "Fuzzy's Taco Shop",
  "GameStop",
  "Gelson's Market",
  "Genesis Health Club",
  "Giant",
  "Giant Eagle Supermarket",
  "Giant Food Store",
  "Giordano's",
  "Gold Star Chili",
  "Gold's Gym",
  "Golden Chick",
  "Golden Corral",
  "Golf Galaxy",
  "Good Times Burgers & Frozen Custard",
  "Grandy's",
  "Grocery Outlet Bargain Market",
  "Guitar Center",
  "H Mart",
  "H-E-B",
  "Half Price Books",
  "Hampton Inn",
  "Hannaford",
  "Happy Joe's",
  "Harbor Freight Tools",
  "Hardee's",
  "Harkins Theatres",
  "Harmons Grocery",
  "Harris Teeter",
  "Hartz Chicken Buffet",
  "Havertys",
  "Havoline Xpress Lube",
  "Hawthorn Suites by Wyndham",
  "HCA Healthcare",
  "Heinen's Grocery Store",
  "Hilton Garden Inn",
  "Hobby Lobby",
  "Holiday Inn",
  "Holiday Inn Express",
  "HomeGoods",
  "Homesense",
  "HomeTown Buffet",
  "Homewood Suites by Hilton",
  "Hooters",
  "Hotel Indigo",
  "Houlihan's",
  "Howard Johnson",
  "Huddle House",
  "Hy-Vee",
  "Hyatt Hotels & Resorts",
  "IHOP",
  "IKEA",
  "Imo's Pizza",
  "In-N-Out Burger",
  "In-Shape Health Clubs",
  "Ingles",
  "Interstate Batteries",
  "InTown Suites",
  "InvenTrust Properties",
  "Islands Restaurant",
  "Jack in the Box",
  "Jack's Family Restaurants",
  "Jared The Galleria of Jewelry",
  "Jason's Deli",
  "JCPenney",
  "Jeremiah's Italian Ice",
  "Jewel-Osco",
  "Jiffy Lube",
  "Jimmy's Egg",
  "Jo-Ann Fabric and Craft",
  "Joe's Crab Shack",
  "Johnny Carino's",
  "Just Tires",
  "K & G",
  "Keke's Breakfast Cafe",
  "KFC",
  "Kimco Realty",
  "King Soopers",
  "Kinney Drugs",
  "Kirkland’s",
  "Kite Realty Group",
  "Kmart",
  "Kneaders Bakery & Cafe",
  "Kohl's",
  "Krispy Kreme Doughnuts",
  "Kroger",
  "Krystal",
  "L.L.Bean",
  "LA Fitness",
  "la Madeleine Country French Café",
  "La-Z-Boy",
  "Label Shopper",
  "Lamps Plus",
  "Lane Bryant",
  "Lassens Natural Foods and Vitamins",
  "Leo's Coney Island",
  "Les Schwab Tire Center",
  "Lidl",
  "Life Time",
  "Lion's Choice",
  "Logan's Roadhouse",
  "Long John Silver's",
  "LongHorn Steakhouse",
  "Lord & Taylor",
  "Lowe's",
  "Lowes Foods",
  "Luby's",
  "Lucky",
  "LL Flooring",
  "Inc.",
  "Lunds & Byerlys",
  "Macerich Mall Properties",
  "Macy's",
  "Maggiano's Little Italy",
  "Main Event Entertainment",
  "MainStay Suites",
  "Marc's",
  "Mariano's Fresh Market",
  "Market Basket",
  "Market Basket Foods",
  "Marlow's Tavern",
  "Marshalls",
  "Mason Asset Management",
  "Mazzio's Pizza",
  "McAlister's Deli",
  "McCoy's Building Supply",
  "McDonald's",
  "Me-N-Ed's Pizzeria",
  "MedExpress Urgent Care",
  "Meijer",
  "Meineke Car Care Center",
  "Mellow Mushroom",
  "Men's Wearhouse",
  "Menards",
  "Metro Diner",
  "MGM Resorts Casinos",
  "Michaels",
  "Micro Center",
  "Microtel Inn & Suites",
  "Midas",
  "Miguel's Jr",
  "Miller's Ale House",
  "Mills Fleet Farm",
  "Mimi's Cafe",
  "Mission BBQ",
  "Modell's Sporting Goods",
  "Moe's Original Bar B Que",
  "Motel 6",
  "Mountainside Fitness",
  "Mr. Tire",
  "Murdoch's Ranch & Home Supply",
  "Native Grill & Wings",
  "Natural Grocers",
  "Neiman Marcus",
  "New Seasons Market",
  "Newk's Eatery",
  "Nike Factory Store",
  "Nob Hill Foods",
  "Nordstrom",
  "Nordstrom Rack",
  "Northern Tool & Equipment",
  "Northgate Gonzalez Markets",
  "Nothing Bundt Cakes",
  "NTB - National Tire & Battery",
  "O'Charley's",
  "O'Reilly Auto Parts",
  "Oberweis Dairy",
  "Ocean State Job Lot",
  "Off Broadway Shoe Warehouse",
  "Office Depot",
  "OfficeMax",
  "Old Chicago",
  "Old Navy",
  "Olive Garden",
  "Ollie's Bargain Outlet",
  "On The Border Mexican Grill & Cantina",
  "Orscheln Farm & Home",
  "Outback Steakhouse",
  "P.C. Richard & Son",
  "P.F. Chang's",
  "Pancheros Mexican Grill",
  "Panda Express",
  "Panera Bread",
  "Papa Gino's",
  "Papa John's Pizza",
  "Pappadeaux Seafood Kitchen",
  "Party City",
  "Pavilions",
  "Pei Wei",
  "Pennsylvania Real Estate Investment Trust",
  "Pep Boys Auto Parts & Service",
  "Perkins Restaurant & Bakery",
  "Pet Food Express",
  "Pet People",
  "Pet Supermarket",
  "Pet Supplies Plus",
  "Petco",
  "Peter Piper Pizza",
  "PetSmart",
  "Phillips Edison Properties",
  "Pick 'n Save",
  "Pier 1 Imports",
  "Piggly Wiggly",
  "Pizza Factory",
  "Pizza Hut",
  "Pizza Patron",
  "Pizza Ranch",
  "Plaid Pantry",
  "Planet Fitness",
  "Plaza Tire Service",
  "PNC Bank",
  "Pollo Campero",
  "Pollo Tropical",
  "Ponderosa",
  "Popeyes Louisiana Kitchen",
  "Powerhouse Gym",
  "Precision Tune Auto Care",
  "Presidente Supermarkets",
  "Price Chopper (Golub)",
  "Publix",
  "Pyramid Management Group",
  "Qdoba Mexican Grill",
  "QFC",
  "Quaker Steak & Lube",
  "Quality Inn",
  "QuikTrip",
  "Raising Cane's Chicken Fingers",
  "Raley's",
  "Rally's",
  "Ralphs",
  "Ramco-Gershenson Properties Trust",
  "Ray's Food Place",
  "Raymour & Flanigan Furniture Store",
  "Red Lobster",
  "Red Robin Gourmet Burgers",
  "Red Roof Inn",
  "Reebok Outlet",
  "Regal Cinemas",
  "Regency Centers",
  "Regions Bank",
  "REI",
  "Residence Inn by Marriott",
  "Restaurant Depot",
  "Retail Opportunity Investments Corporation",
  "Retro Fitness",
  "RibCrib",
  "Rite Aid",
  "Romano's Macaroni Grill",
  "Rosa's Cafe",
  "Rosauers",
  "Ross Dress for Less",
  "Round Table Pizza",
  "Rouses Market",
  "Roy Rogers",
  "Royal Farms",
  "RPT Realty",
  "Ruby Tuesday",
  "Runza",
  "Rural King",
  "Ruth's Chris Steak House",
  "Safeway",
  "Saks OFF 5TH",
  "Salon Lofts",
  "Salsarita's Fresh Cantina",
  "Saltgrass Steak House",
  "Sam's Club",
  "Save Mart",
  "Save-A-Lot",
  "Schnucks",
  "Sears Auto Center",
  "Sears Hometown Stores",
  "Seasons 52",
  "Sedano's",
  "Shari's",
  "Sharky's Woodfired Mexican Grill",
  "Shaw's Supermarket",
  "Shipley Do-Nuts",
  "Shoe Carnival",
  "Shoney's",
  "ShopRite",
  "Showmars",
  "Sierra",
  "Simon Properties Group",
  "Sizzler",
  "Sky Zone Trampoline Park",
  "Skyline Chili",
  "Sleep Inn",
  "Slim Chickens",
  "Slumberland Furniture",
  "Smart & Final",
  "Smith's",
  "Smithfield's Chicken 'N Bar-B-Q",
  "Smokey Bones Bar & Fire Grill",
  "SONIC Drive In",
  "Sonny's BBQ",
  "Spec's",
  "Sportsman's Warehouse",
  "Springhill Suites",
  "Sprouts Farmers Market",
  "Staples",
  "Staybridge Suites",
  "Steak 'n Shake",
  "Stein Mart",
  "Stop & Shop",
  "Studio Movie Grill",
  "Sullivan Tire",
  "Suntrust Bank",
  "Super 1 Foods",
  "Super 1 Foods & Pharmacy",
  "Super 8",
  "Superior grocers",
  "Sweet Tomatoes",
  "T.J. Maxx",
  "Taco Bell",
  "Taco Bueno",
  "Taco Cabana",
  "Taco Casa",
  "Taco John's",
  "Taco Mayo",
  "Taco Time",
  "Take 5 Oil Change",
  "Tanger Outlets",
  "Target",
  "Taubman Properties",
  "TD Bank",
  "Ted's Montana Grill",
  "Tenet Healthcare",
  "Texas de Brazil",
  "Texas Roadhouse",
  "Texas Tires",
  "TGI Fridays",
  "The Brass Tap",
  "The Capital Grille",
  "The Cheesecake Factory",
  "The Container Store",
  "The Edge Fitness Club",
  "The Fresh Market",
  "The Greene Turtle",
  "The Home Depot",
  "The Melting Pot",
  "The Original Pancake House",
  "Tim Hortons",
  "Tire Discounters",
  "Tire Kingdom",
  "Tires Plus",
  "Topgolf",
  "Tops Friendly Markets",
  "Total Wine & More",
  "Town Fair Tire",
  "TownePlace Suites by Marriott",
  "Tractor Supply Co.",
  "Trader Joe's",
  "Travelodge",
  "Tread Quarters",
  "Tubby's",
  "Twin Peaks",
  "Twin River Casinos",
  "Ulta Beauty",
  "Uncle Julio's",
  "Union Bank",
  "United Bank",
  "Universal Healthcare",
  "Uno Chicago Grill",
  "Urban Edge Properties",
  "Vallarta Supermarket",
  "Value City Furniture",
  "Valvoline Instant Oil Change",
  "Vasa Fitness",
  "VF Outlet",
  "Von Maur",
  "VONS",
  "Waffle House",
  "Walgreens",
  "Walmart",
  "Walmart Neighborhood Market",
  "Washington Prime Group",
  "Wawa",
  "Wegmans",
  "Weis Markets",
  "Wells Fargo",
  "Wendy's",
  "West Elm",
  "Western Sizzlin",
  "Westfield",
  "Whataburger",
  "White Castle",
  "Whole Foods Market",
  "Wienerschnitzel",
  "Wild Wing Cafe",
  "WinCo Foods",
  "Wingate By Wyndham",
  "Winn-Dixie",
  "World of Beer",
  "WSS",
  "Wynn Resorts",
  "XSport Fitness",
  "Yard House",
  "Yoshinoya",
  "Youfit Health Clubs",
  "Your Pie",
  "Yum Yum Donuts",
  "Zaxby's Chicken Fingers & Buffalo Wings",
  "Zoes Kitchen",
];
for (let i = 0; i <= brandOptions.length; i++) {
  var opt = document.createElement("option");
  opt.value = i;
  opt.innerHTML = i;
  select.appendChild(opt);
}
